import React from "react";

export default function TableOfContents() {
  return (
    <div className="TableOfContents">
      TableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContentsTableOfContents
    </div>
  );
}
